Do not probe host groups without need. Fix multi-line scanner errors.

diff --git a/polscan b/polscan
--- a/polscan
+++ b/polscan
@@ -39,20 +39,20 @@ fi
 
 # 1. If none given determine host list automatically
 if [ "$HOST_LIST" == "" ]; then 
-	for h in $HOST_LIST_PROVIDER; do
-		echo "Fetching host list (provider '$h')..."
-		HLP="$LIB_DIR/host-list-providers/$h"
-		if [ ! -f "$HLP" ]; then
-			echo "ERROR: Could not find host list provider $HLP"
-			exit 1
-		fi
-		HOST_LIST="${HOST_LIST}
+        for h in $HOST_LIST_PROVIDER; do
+                echo "Fetching host list (provider '$h')..."
+                HLP="$LIB_DIR/host-list-providers/$h"
+                if [ ! -f "$HLP" ]; then
+                        echo "ERROR: Could not find host list provider $HLP"
+                        exit 1
+                fi
+                HOST_LIST="${HOST_LIST}
 $($HLP)"
-		if [ $? -ne 0 ]; then
-			echo "ERROR: Could not determine '$h' host list!"
-			exit 1
-		fi
-	done
+                if [ $? -ne 0 ]; then
+                        echo "ERROR: Could not determine '$h' host list!"
+                        exit 1
+                fi
+        done
 fi
 
 if [ "$HOST_LIST" == "" ]; then
@@ -61,8 +61,6 @@ if [ "$HOST_LIST" == "" ]; then
 else
 	echo "Host list:" $HOST_LIST
 fi
-
-load_host_groups
 
 REMOTE_SCANNER_LIST=$(get_scanners remote)
 if [ "$REMOTE_SCANNER_LIST" != "" ]; then
@@ -103,7 +101,7 @@ if [ "$REMOTE_SCANNER_LIST" != "" ]; then
 			# to track under name "polscan"
 			(
 				errors=$(grep -v "$REMOTE_STDERR_WHITELIST" "${RESULT_DIR}/${host}.err" 2>/dev/null)
-				printf "%s" "$errors" | sed "s/^/Polscan FAILED |||Polscan remote scan||| /"
+				printf "%s\n" "$errors" | grep -v '^$' | sed "s/^/Polscan FAILED |||Polscan remote scan||| /"
 			) >>"${RESULT_DIR}/$host"
 			rm "${RESULT_DIR}/${host}.err"
 		fi
