Implement concurrent remote scans using xargs

diff --git a/polscan b/polscan
--- a/polscan
+++ b/polscan
@@ -2,7 +2,7 @@
 
 # Polscan: a Debian policy scanner
 
-# Copyright (C) 2015-2016  Lars Windolf <lars.windolf@gmx.de>
+# Copyright (C) 2015-2017  Lars Windolf <lars.windolf@gmx.de>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -31,50 +31,6 @@ NON_INTERACTIVE=$(/usr/bin/tty -s; echo $?)
 
 # Command line parsing, setup environment
 source "$LIB_DIR/polscan-common.inc"
-
-###############################################################################
-# Prints progress bar when in interactive shell, otherwise just a single
-# line with currently processed host
-#
-# $1 	current host
-###############################################################################
-declare -A progress
-OK_COLOR=$(/usr/bin/tput setab 2; /usr/bin/tput setaf 0)
-FAILED_COLOR=$(/usr/bin/tput setab 1; /usr/bin/tput setaf 0)
-WARNING_COLOR=$(/usr/bin/tput setab 3; /usr/bin/tput setaf 0)
-RESET_COLOR=$(/usr/bin/tput sgr0)
-
-print_progress() {
-	host=$1
-	progress[host_count]=$(( ${progress[host_count]-0} + 1 ))
-
-	if [[ ${progress[hosts_total]} = "" ]]; then
-		progress[hosts_total]=$(echo $HOST_LIST | wc -w)
-		printf "\n\n\n\n"
-	fi
-
-	if [[ $NON_INTERACTIVE -eq 1 ]]; then
-		printf " -> %s [%d/%d]\n" "$remote" "${progress[host_count]}" "${progress[hosts_total]}"
-	else
-		# Get result statistics
-		if [ -f "$RESULT_DIR/$host" ]; then
-			progress[result_count]=$((${progress[result_count]-0} + $(grep -c ' |||' "$RESULT_DIR/$host" 2>/dev/null)))
-			progress[failed_count]=$((${progress[failed_count]-0} + $(grep -c ' FAILED ' "$RESULT_DIR/$host" 2>/dev/null)))
-			progress[warning_count]=$((${progress[warning_count]-0} + $(grep -c ' WARNING ' "$RESULT_DIR/$host" 2>/dev/null)))
-			progress[ok_count]=$((${progress[ok_count]-0} + $(grep -c ' OK ' "$RESULT_DIR/$host" 2>/dev/null)))
-		fi
-
-		# FIXME: Colors only on color capable terminals
-		printf "sc\ncuu 4\nel1\nel\n" | /usr/bin/tput -S
-		echo "---------------------------------------------------------"
-		/usr/bin/tput el
-		printf "Scanning %s (%d/%d)\n" "$remote" "${progress[host_count]}" "${progress[hosts_total]}"
-		/usr/bin/tput el
-		printf "Results: Overall %d (%s %d %s / %s %d %s / %s %d %s)\n" "${progress[result_count]}" "$FAILED_COLOR" "${progress[failed_count]}" "$RESET_COLOR" "$WARNING_COLOR" "${progress[warning_count]}" "$RESET_COLOR" "$OK_COLOR" "${progress[ok_count]}" "$RESET_COLOR"
-		echo "---------------------------------------------------------"
-		/usr/bin/tput rc
-	fi
-}
 
 # 0. Prepare output dir
 if [ ! -d "$RESULT_DIR" ]; then
@@ -128,36 +84,29 @@ if [ "$REMOTE_SCANNER_LIST" != "" ]; then
 	done
 
 	echo "Running remote scans..."
-	for remote in $HOST_LIST; do
-		current_host=${remote/*@/}
 
-		if ! echo "$remote" | grep -q @; then
-			# Default user if none given from host list and SSH_USER is set
-			if [ "$SSH_USER" != "" ]; then
-				remote=$SSH_USER@$remote
-			fi
-		fi
+	remotes=${HOST_LIST}
+	if [ "$SUDO_CMD" != "" ]; then
+		# Suffix host names with sudo command
+		remotes=$(echo $remotes | xargs -n 1 | sed "s/\$/ ${SUDO_CMD}/")
+	fi
+	
+	echo "$remotes" | xargs -n1 --replace={} -n 1 -P ${SCAN_CONCURRENCY-15} \
+	/bin/bash -c "host='{}';printf '%s\n' \"\${host/ */}\" && \
+	              $SSH_CMD {} \"/bin/bash < <(/bin/cat -)\" <${RSS} >${RESULT_DIR}/\${host/ */} 2>${RESULT_DIR}/\${host/ */}.err || :"
 
-		if ! echo "$remote" | grep -q "root@"; then
-			sudo=$SUDO_CMD
-		fi
-
-		$SSH_CMD "$remote" "$sudo" "/bin/bash < <(/bin/cat -)" \
-			<"$RSS" \
-			>"${RESULT_DIR}/$current_host" \
-			2>"${RESULT_DIR}/${current_host}.err"
-
-		if [ $? -ne 0 ]; then
+	# Post process all errors logged
+	for host in $HOST_LIST; do
+		if [ -f ${RESULT_DIR}/${host}.err ]; then
 			# Scanner should never set return code, if we get one
 			# we have a scripting/connectivity issue that we want
 			# to track under name "polscan"
 			(
-				errors=$(grep -v "$REMOTE_STDERR_WHITELIST" "${RESULT_DIR}/${current_host}.err" 2>/dev/null)
-				printf "\nPolscan FAILED |||Polscan remote scan||| %s\n" "$errors"
-			) >>"${RESULT_DIR}/$current_host"
+				errors=$(grep -v "$REMOTE_STDERR_WHITELIST" "${RESULT_DIR}/${host}.err" 2>/dev/null)
+				printf "%s" "$errors" | sed "s/^/Polscan FAILED |||Polscan remote scan||| /"
+			) >>"${RESULT_DIR}/$host"
+			rm "${RESULT_DIR}/${host}.err"
 		fi
-		rm "${RESULT_DIR}/${current_host}.err"
-		print_progress "$current_host"
 	done
 fi
 rm $RSS
