Avoid mixing errors and findings.

diff --git a/polscan b/polscan
--- a/polscan
+++ b/polscan
@@ -95,19 +95,21 @@ if [ "$REMOTE_SCANNER_LIST" != "" ]; then
 			echo " -> $remote"
 		fi
 
-		output=$(/bin/cat $RSS | $SSH_CMD $remote $sudo "/bin/bash < <(/bin/cat -)" 2>&1)
-		(
-			if [ $? -ne 0 ]; then
-				# Scanner should never set return code, if we get one
-				# we have a scripting/connectivity issue that we want
-				# to track under name "polscan"
-				echo "Polscan FAILED |||Polscan remote scan||| $output"
-			else
-				echo "$output"
-			fi
-		) |\
-		grep -v 'Warning: Permanently added.*to the list of known hosts.' \
-		> ${RESULT_DIR}/$current_host
+		/bin/cat $RSS | $SSH_CMD $remote $sudo "/bin/bash < <(/bin/cat -)" \
+			>${RESULT_DIR}/$current_host \
+			2>${RESULT_DIR}/${current_host}.err
+
+		if [ $? -ne 0 ]; then
+			# Scanner should never set return code, if we get one
+			# we have a scripting/connectivity issue that we want
+			# to track under name "polscan"
+			(
+				errors=$(grep -v 'Warning: Permanently added.*to the list of known hosts.' ${RESULT_DIR}/${current_host}.err 2>/dev/null)
+				echo "Polscan FAILED |||Polscan remote scan||| $errors"
+			) >>${RESULT_DIR}/$current_host
+			rm ${RESULT_DIR}/${current_host}.err
+		fi
+
 		i=$(( $i + 1 ))
 	done
 fi
