Allow passing a host list. Check for standalone.conf to avoid errors.

diff --git a/polscan b/polscan
--- a/polscan
+++ b/polscan
@@ -18,17 +18,21 @@ if [ ! -d $RESULT_DIR ]; then
 	mkdir -vp "$RESULT_DIR"
 fi
 
-# 1. Determine host list
-echo "Fetching host list (provider '$HOST_LIST_PROVIDER')..."
-HLP="$LIB_DIR/host-list-providers/$HOST_LIST_PROVIDER"
-if [ ! -f $HLP ]; then
-	echo "ERROR: Could not find host list provider $HLP"
-	exit 1
-fi
-HOST_LIST=$($HLP)
-if [ $? -ne 0 ]; then
-	echo "ERROR: Could not determine '$HOST_LIST_PROVIDER' host list!"
-	exit 1
+# 1. If none given determine host list
+if [ "$1" == "" ]; then 
+	echo "Fetching host list (provider '$HOST_LIST_PROVIDER')..."
+	HLP="$LIB_DIR/host-list-providers/$HOST_LIST_PROVIDER"
+	if [ ! -f $HLP ]; then
+		echo "ERROR: Could not find host list provider $HLP"
+		exit 1
+	fi
+	HOST_LIST=$($HLP)
+	if [ $? -ne 0 ]; then
+		echo "ERROR: Could not determine '$HOST_LIST_PROVIDER' host list!"
+		exit 1
+	fi
+else
+	HOST_LIST="$1"
 fi
 echo "Host list:" $HOST_LIST
 
@@ -93,19 +97,21 @@ fi
 rm $RSS
 
 # 4. Run standalone scanner scripts
-STANDALONE_SCANNER_LIST=$(grep -v "^ *#" "$STANDALONE_SCANNERS_FILE")
-if [ "$STANDALONE_SCANNER_LIST" != "" ]; then
-	echo "Running standalone scanners..."
-	for scanner in $STANDALONE_SCANNER_LIST; do
-		echo " -> Running '$scanner'..."
-		scanner_file=$LIB_DIR/standalone/$scanner
-		group=`get_policy_group "$scanner_file"`
-		policy=`get_policy_name "$scanner_file"`
-		$scanner_file |\
-		while read host severity data; do
-			echo "$group $severity |||$policy||| $data" >>$RESULT_DIR/$host
+if [ -f $STANDALONE_SCANNERS_FILE ]; then
+	STANDALONE_SCANNER_LIST=$(grep -v "^ *#" "$STANDALONE_SCANNERS_FILE")
+	if [ "$STANDALONE_SCANNER_LIST" != "" ]; then
+		echo "Running standalone scanners..."
+		for scanner in $STANDALONE_SCANNER_LIST; do
+			echo " -> Running '$scanner'..."
+			scanner_file=$LIB_DIR/standalone/$scanner
+			group=`get_policy_group "$scanner_file"`
+			policy=`get_policy_name "$scanner_file"`
+			$scanner_file |\
+			while read host severity data; do
+				echo "$group $severity |||$policy||| $data" >>$RESULT_DIR/$host
+			done
 		done
-	done
+	fi
 fi
 
 $BASE/polscan_html
