Add new policy for reverse lookups. Fix output typo and comment typo.

diff --git a/lib/host-group-providers/auto_detect b/lib/host-group-providers/auto_detect
--- a/lib/host-group-providers/auto_detect
+++ b/lib/host-group-providers/auto_detect
@@ -36,5 +36,5 @@ for p in $(ls | grep -v auto_detect); do
 done
 
 if [ $found_some -ne 1 ]; then
-	echo "ERROR: No suitable host list provider!" >&2
+	echo "ERROR: No suitable host group provider!" >&2
 fi
